// <auto-generated />
using System;
using AQI_Monitoring_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AQI_Monitoring_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250331152419_AddPollutantFields")]
    partial class AddPollutantFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AQI_Monitoring_System.Models.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxAqi")
                        .HasColumnType("int");

                    b.Property<int>("MinAqi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlertThresholds");
                });

            modelBuilder.Entity("AQI_Monitoring_System.Models.AqiReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aqi")
                        .HasColumnType("int");

                    b.Property<double?>("Co")
                        .HasColumnType("double");

                    b.Property<double?>("No2")
                        .HasColumnType("double");

                    b.Property<double?>("O3")
                        .HasColumnType("double");

                    b.Property<double?>("Pm10")
                        .HasColumnType("double");

                    b.Property<double?>("Pm25")
                        .HasColumnType("double");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("So2")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("AqiReadings", (string)null);
                });

            modelBuilder.Entity("AQI_Monitoring_System.Models.Sensor", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("AQI_Monitoring_System.Models.SimulationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaselineAqi")
                        .HasColumnType("int");

                    b.Property<double>("BaselineCo")
                        .HasColumnType("double");

                    b.Property<double>("BaselineNo2")
                        .HasColumnType("double");

                    b.Property<double>("BaselineO3")
                        .HasColumnType("double");

                    b.Property<double>("BaselinePm10")
                        .HasColumnType("double");

                    b.Property<double>("BaselinePm25")
                        .HasColumnType("double");

                    b.Property<double>("BaselineSo2")
                        .HasColumnType("double");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<double>("VariationCo")
                        .HasColumnType("double");

                    b.Property<double>("VariationNo2")
                        .HasColumnType("double");

                    b.Property<double>("VariationO3")
                        .HasColumnType("double");

                    b.Property<double>("VariationPm10")
                        .HasColumnType("double");

                    b.Property<double>("VariationPm25")
                        .HasColumnType("double");

                    b.Property<int>("VariationRange")
                        .HasColumnType("int");

                    b.Property<double>("VariationSo2")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("SimulationConfigs");
                });

            modelBuilder.Entity("AQI_Monitoring_System.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AQI_Monitoring_System.Models.AqiReading", b =>
                {
                    b.HasOne("AQI_Monitoring_System.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
